# Created using CreateManifest.ps1 v0.3.0
# yaml-language-server: $schema=https://raw.githubusercontent.com/Per-Terra/butler-pkgs/main/schemas/JSON/manifest/0.3.0.json

Identifier: L-SMASH-Works
DisplayName: L-SMASH Works
Version: r1151
ReleaseDate: 2025-07-06
Section: Plugin/Input
Architecture: x64
InstalledSize: 43484266
Developer:
- Mr-Ojii
Description: AviUtl用入力プラグインその他
Website:
- https://github.com/Mr-Ojii/L-SMASH-Works-Auto-Builds
Files:
- SourceUrl: https://github.com/Mr-Ojii/L-SMASH-Works-Auto-Builds/releases/download/build-2025-07-06-01-25-30/L-SMASH-Works_r1151_Mr-Ojii_vimeo.zip
  SHA256: 92c03c16ba5ad2d144421b43e311b300763ab02a3804c06782671fa8ba2899da
  Files:
  - Path: About-this-build.txt
    SHA256: baa14185120d630269820ce796a6e18e8ffac5868a5ec96c7252f449e841e3d2
  - Path: LICENSE
    SHA256: 5ec6a5ca2e945b59be4c71cb2955575ae615532a8af201efd79b79d467421e5f
  - Path: lwcolor.auc
    SHA256: 5d7d0a5c3471cf09eaf41c1a1412de9ff6323e627fc4714382d3ed25c1f3dd1c
    Install:
      TargetPath: plugins/lwcolor.auc
  - Path: lwdumper.auf
    SHA256: 2ec4c7976c7760dbb7d0dbee0e6139ada51c1d53681f4f2d0ca15e4b10e45c3c
    Install:
      TargetPath: plugins/lwdumper.auf
  - Path: lwinput.aui
    SHA256: fa05a5bc1c762194c70826453610d98657c252e248f1799fd71cec79c8c85d8b
    Install:
      TargetPath: plugins/lwinput.aui
  - Path: lwinput64.aui
    SHA256: 04f0d0d252457ad677247443809e40f060b37c5c936cd4761ae79e2dccceba7e
    Install:
      TargetPath: plugins/lwinput64.aui
  - Path: lwmuxer.auf
    SHA256: 332debf01f90557c7c6e0c9fd18776892d4ec4bd3571dbb7b9b368ea6afc1866
    Install:
      TargetPath: plugins/lwmuxer.auf
  - Path: README
    SHA256: 809cb8613a4f5fe8e68b3196cac3a00e474251208da771ffb4c3c42907fad178
  - Path: README.ja
    SHA256: 65916cd6fbc0b9a1cdd188e5457544c24a571a4d00645306be4cbb88af1effbe
  - Path: Licenses/dav1d.txt
    SHA256: b327887de263238deaa80c34cdd2ff3e0ba1d35db585ce14a37ce3e74ee389e9
  - Path: Licenses/FFmpeg.txt
    SHA256: da7eabb7bafdf7d3ae5e9f223aa5bdc1eece45ac569dc21b3b037520b4464768
  - Path: Licenses/game-music-emu.txt
    SHA256: d2efc89fbb7533572a472d34e07964951810a3a4f8d3159ecc2dcaa1452c5c26
  - Path: Licenses/L-SMASH.txt
    SHA256: f778761540555e63528418e75784c0ed7bf2b89ab11f5ddbfd4bec7aa540e79d
  - Path: Licenses/libvpl.txt
    SHA256: bf1cfac2e2792b6e1e995ce103d70796aecaf2ec7e4c5fe5474f7acec7b4a677
  - Path: Licenses/libvpx.txt
    SHA256: 8267348d5af1262c11d1a08de2f5afc77457755f1ac658627dd9acf71011d615
  - Path: Licenses/obuparse.txt
    SHA256: c2a92a24f409940e3d510ba5e8c520141dc103748d7d0d23798364cc160bd074
  - Path: Licenses/zlib.url
    SHA256: 9b12c6736fbf96980bf484c3d83d7f12f54e9c08b5318b06b47a4628a93557dd
Plugins:
- Name: LW ColorSpace
  Information: L-SMASH Works Color Space Converter r1151 by Mr-Ojii
  Type: Color
  InstallPath: plugins/lwcolor.auc
- Name: L-SMASH Works Dumper
  Information: L-SMASH Works Dumper r1151 by Mr-Ojii
  Type: Filter
  InstallPath: plugins/lwdumper.auf
- Name: L-SMASH Works File Reader
  Information: L-SMASH Works File Reader r1151 by Mr-Ojii
  Type: Input
  InstallPath: plugins/lwinput.aui
- Name: L-SMASH Works Muxer
  Information: L-SMASH Works Muxer r1151 by Mr-Ojii
  Type: Filter
  InstallPath: plugins/lwmuxer.auf
ManifestVersion: 0.3.0
