# Created using CreateManifest.ps1 v0.3.0
# yaml-language-server: $schema=https://raw.githubusercontent.com/Per-Terra/butler-pkgs/main/schemas/JSON/manifest/0.3.0.json

Identifier: LuaJIT
Version: "2.1"
ReleaseDate: 2026-03-01
Section: Core
Architecture: x86
Replaces:
- exedit
InstalledSize: 1235542
Developer:
- Per-Terra
Description: Per-TerraによるLuaJITの自動ビルド
Website:
- https://github.com/Per-Terra/LuaJIT-Auto-Builds
Files:
- SourceUrl: https://github.com/Per-Terra/LuaJIT-Auto-Builds/releases/download/build-2026-03-01-01-26-10/LuaJIT_2.1_Win_x86.zip
  SHA256: 1d9f3d02c74ce038eb77b0bfdba5a4258c02e4d37fb3b9e83372caf04420f890
  Files:
  - Path: About-This-Build.txt
    SHA256: b2aae6a1208ebac472681da537b1043496cad7ba0e5c0c585bc63567b2eddc03
  - Path: COPYRIGHT
    SHA256: 1b10a02c9474cb908da2d87bc908edd8798f9ad28d9a8c53fbd05c13227f7394
  - Path: lua51.dll
    SHA256: 61f6aaa69bd26cb04a109bc4ed10be5634ef4d30e6298f0dde749a66c264314b
    Install:
      TargetPath: lua51.dll
  - Path: luajit.exe
    SHA256: 506f9ae34db3bbc95c51aca2043eb34431937e077676bbc7d439d1218d1a680d
  - Path: README
    SHA256: 63a5cebd3b3bf0adad4c8cbf470bca5ab62f668d0de38e878b5fd70bc1c6c8db
  - Path: doc/bluequad-print.css
    SHA256: 85accb9a92e6947b2dd6791ceebe052da13e4270f994623b7376420943b7dccf
  - Path: doc/bluequad.css
    SHA256: a2073eb129749da4ef9e2d0c83594fba075cc22b9b644c7b5c14508bbca01fcf
  - Path: doc/contact.html
    SHA256: cd277ad453ee2351c75f48209ae79d04fdc8f3ce8daa015f89a996548c73c4f2
  - Path: doc/ext_buffer.html
    SHA256: a92278c930c186c579b0945de3068e94f2a624670567d3efd68bdbad8d51731c
  - Path: doc/ext_c_api.html
    SHA256: 1e4c7f55d60428976d0d3f838fc59e418a1292daddd182fae804c5d2ce1a1164
  - Path: doc/ext_ffi_api.html
    SHA256: fe9b873f738a4a3887261df9a01b8d064caca949112d6aa7599f0d7cae8e0055
  - Path: doc/ext_ffi_semantics.html
    SHA256: fe8165c9f4f4d5aa3cacd093a4bc8d746d82365361c9398560252fdb044e48c3
  - Path: doc/ext_ffi_tutorial.html
    SHA256: e24a9193121b442ac3eb14b2383cae5f76190ae49249b2fc4328c33d5864eaf1
  - Path: doc/ext_ffi.html
    SHA256: c92c62230ff4c52e44ebbfdc0873edb3ce97ef4c62a9998cccdd0a2e62347f2e
  - Path: doc/ext_jit.html
    SHA256: 9a9dc0ccec3ad725d8a3b2887f5812af57f5a137ab51650aa746b963ddf8fb31
  - Path: doc/ext_profiler.html
    SHA256: 7bd41c8105aff65ea664bbf98397c28c84cfac907825665f57c46710d155b311
  - Path: doc/extensions.html
    SHA256: dd1872872ac65d088f30c0f0ebe73ae0acdea718d9e10043c474c8cc7d2b6405
  - Path: doc/install.html
    SHA256: 5eb4cd5cc48c52f06050d4000b4932127401d0b8e74e40e998b559797185ea11
  - Path: doc/luajit.html
    SHA256: da6fc0ca5e72e873f58f152c1cb2b448e3c03cfb1e97e4a11e2b573756f098dd
  - Path: doc/running.html
    SHA256: 6f823a50c9ee7e0e816496c051b7d7e9acb0ecd7d924357fc5aa4649771382a1
  - Path: doc/img/contact.png
    SHA256: 9b89eddcb7af5b0cc62a4cba4f878dcde584f378763e4d74621d44130a1ebec0
ManifestVersion: 0.3.0
