# Created using CreateManifest.ps1 v0.3.0
# yaml-language-server: $schema=https://raw.githubusercontent.com/Per-Terra/butler-pkgs/main/schemas/JSON/manifest/0.3.0.json

Identifier: LuaJIT
Version: "2.1"
ReleaseDate: 2026-01-06
Section: Core
Architecture: x86
Replaces:
- exedit
InstalledSize: 1234931
Developer:
- Per-Terra
Description: Per-TerraによるLuaJITの自動ビルド
Website:
- https://github.com/Per-Terra/LuaJIT-Auto-Builds
Files:
- SourceUrl: https://github.com/Per-Terra/LuaJIT-Auto-Builds/releases/download/build-2026-01-06-01-05-22/LuaJIT_2.1_Win_x86.zip
  SHA256: 54ce5a02c145c374e77149dcf00fd9384c2fa6a55d7663348112725c1c94d8db
  Files:
  - Path: About-This-Build.txt
    SHA256: 33706c5f9c11f105b8d6eeb13de3800e32b828f3a0ee86ec639ac42d2a8dbed9
  - Path: COPYRIGHT
    SHA256: c5bbe7ecf4ae277ed8e1485a65f9e6c7e1ab9004e6ddf2b48d61e80e572140dd
  - Path: lua51.dll
    SHA256: ce92fc74d43755cc6cc63ac143ea69816e9aedf9ce508b42eb6950fc3ab0fda3
    Install:
      TargetPath: lua51.dll
  - Path: luajit.exe
    SHA256: 2d4d11bf54dc2c2045f13c2d3f7a393eafc02f860da4792ccefe534f1d3dcf26
  - Path: README
    SHA256: 909348cbfccb03242ca8282cd0c6978977103c81f9fab6fbe9514bc5a63d0c75
  - Path: doc/bluequad-print.css
    SHA256: 3784e5f44be4c2ce381b5c91ed5a92197e387fdc13234798cd2aa3044fdb0a76
  - Path: doc/bluequad.css
    SHA256: 79231acc9463246926e2e68e30bbcf7f8338b93a4e89054caad440e931c8f0e4
  - Path: doc/contact.html
    SHA256: 1d80c1f30a78b43af1850540ec1d604054f315096cb737e16a1a70e71f4d7e5d
  - Path: doc/ext_buffer.html
    SHA256: be767bb39e5b1db6d466b4e756ab43980851e7df4d5b6054e5cab1c63379c6f7
  - Path: doc/ext_c_api.html
    SHA256: 28ee628f2051c3149a8de5cddbc22cd73c6c9a86b893a0d9b21837ca3dead90d
  - Path: doc/ext_ffi_api.html
    SHA256: 8688f9c42f5a9ef0724a3ed49fc21d2eab3bd64847dea48f6e48fcfea6d71242
  - Path: doc/ext_ffi_semantics.html
    SHA256: ca709f3c96bab3a9495f8195fb384c1cb1d5dc5d11ddbef9b934a5aec043e70a
  - Path: doc/ext_ffi_tutorial.html
    SHA256: baec7a26262a569f0b7db516940939cdbeafcc86ebdd66f16774b2dec7166ab1
  - Path: doc/ext_ffi.html
    SHA256: 092173b7caa3a2005bd2f1fefcd540811eb080ea0bc1d75e2d4a887376fd166e
  - Path: doc/ext_jit.html
    SHA256: b8afaae3e78c330d47097626863250f343be2f003024b62853e0756d1f69ea02
  - Path: doc/ext_profiler.html
    SHA256: 96034022929bb035f84ea71ff22cc4ac5a16d555fab5f1ec78d2d480c4a5fad9
  - Path: doc/extensions.html
    SHA256: 996fa8be295aedae5764f51315bd58aa8d6b30cfbb95cca2ba2d22697e48394f
  - Path: doc/install.html
    SHA256: 56a3d6ddef832d5b8697079e66ef7ed7cd715319d9735ca33a64646e9bb7a3b2
  - Path: doc/luajit.html
    SHA256: 215a54a2e1a079aa47ab431c7ca5589ae5d4ae26dee2e46e851f1602bd886ea2
  - Path: doc/running.html
    SHA256: c548d66bac2eca53b7f40e42cba16db7928202e059e688358e19f697b6ea763b
  - Path: doc/img/contact.png
    SHA256: 9b89eddcb7af5b0cc62a4cba4f878dcde584f378763e4d74621d44130a1ebec0
ManifestVersion: 0.3.0
