# Created using CreateManifest.ps1 v0.2.0
# yaml-language-server: $schema=https://raw.githubusercontent.com/Per-Terra/butler-pkgs/main/schemas/JSON/manifest/0.2.0.json

Identifier: LuaJIT
Version: "2.1"
ReleaseDate: 2024-07-30
Section: Core
Architecture: x86
Replaces:
- exedit
InstalledSize: 1190
Developer:
- Per-Terra
Description: Per-TerraによるLuaJITの自動ビルド
Website:
- https://github.com/Per-Terra/LuaJIT-Auto-Builds
Files:
- SourceUrl: https://github.com/Per-Terra/LuaJIT-Auto-Builds/releases/download/build-2024-07-30-00-44-29/LuaJIT_2.1_Win_x86.zip
  Sha256: 07617a22bde9ec7c12826985fe70307cd60b378f4525f93bdb8f4d2ded0b9e54
  Files:
  - Path: About-This-Build.txt
    Sha256: 2175b1a779ae6a51e6fd0e967a865deb4ea12bed7ad59e6c6fabe177ba714952
  - Path: COPYRIGHT
    Sha256: 4e546dc0556ca5f1514ae9d9bad723501a51da556342590b7076fb42f2930f25
  - Path: lua51.dll
    Sha256: 029f4b299d222aec162ef890d48c4808ea437febc31e116e0a7906449f1b4c3b
    Install:
      TargetPath: lua51.dll
  - Path: luajit.exe
    Sha256: 8f84de2aa052348007317e68fd9dd1493233b68678caec4627ef0b2968b9c403
  - Path: README
    Sha256: dad6aa1f8fca498b4bacac8b19d9a1d7b0eb021eed569eb4d76e968c3ea67c87
  - Path: doc/bluequad-print.css
    Sha256: ffbbb7f09ade928758ef126cce208e1e1b1b3771a13f53a63df181192a3ee74d
  - Path: doc/bluequad.css
    Sha256: 13c0f197e8d0d8721880942cc9baf4a10726edfcdbfcd731614d54a19d3382af
  - Path: doc/contact.html
    Sha256: d21d53d5aa52cb662092fbd63da276ac34620c6b2fb495f106540b8c76ee2fe6
  - Path: doc/ext_buffer.html
    Sha256: 1fa0aae34f80235bbf1bf352269e834cc39939e4b027f18f2e7c5c61b7dddba7
  - Path: doc/ext_c_api.html
    Sha256: 0b60d161100b37121eb7d3651f1bf626a4570c30ce71788b5aaf9177a4a8f9c3
  - Path: doc/ext_ffi_api.html
    Sha256: 3041a8b539b5e67f77976bf5dd83a78c8e2b29bbf87ea05e2ed238cb86d9c1ce
  - Path: doc/ext_ffi_semantics.html
    Sha256: 3472858356b69189282b18b7bc3b3fa17ad3e43261004508e33af42251abc5d9
  - Path: doc/ext_ffi_tutorial.html
    Sha256: 00486856af194bc273b7103b0a51d77231c3b3095906c618cd5b02e87dbfc2f0
  - Path: doc/ext_ffi.html
    Sha256: 027b88b085186f519c192f88fd0e2c0a1dbad5a18f8bb647d8b1322e59d2001a
  - Path: doc/ext_jit.html
    Sha256: 6b056e1e9dbc557504bcfd23fa137d79dcaffccd7d03db5702f598d22f8e0d1f
  - Path: doc/ext_profiler.html
    Sha256: e685bdd980785a5fb7fa32ac3feec5576015f2c3fdcf7405088854f96bf9f8b8
  - Path: doc/extensions.html
    Sha256: 8f600208702cf36cfcecac81057ae2af0be0d8c58226ea651ec06adcdc8f1ecb
  - Path: doc/install.html
    Sha256: f64aa02eae7d5668a5d87ac8ce461c9d906f513081d10c24cae7b927813b2d19
  - Path: doc/luajit.html
    Sha256: 436489baf37ef605b888f3e2bae1a4f6605bff4d27ccdd25e7a3ec3d1d2d4907
  - Path: doc/running.html
    Sha256: 0bc889226b56ab20709639d9f13eeefc91ff053cb886e099e28fb270d49a27c0
  - Path: doc/img/contact.png
    Sha256: 9b89eddcb7af5b0cc62a4cba4f878dcde584f378763e4d74621d44130a1ebec0
ManifestVersion: 0.2.0
